### ISSUE TITLE
Great! I love it

### ISSUE THREAD

**Issue by klero2** [efthymios-ks/AVR-IO-Macros#1]
I am a hobbist and arduino entusiast. I play more with AVRs and started to learn the basics or AVR-C. I use another method to set the pins, yours is far easier. 

Just need a the macro to set the INPUT_PULLUP, can you add it?

**Comment by efthymios-ks** [comment]
Hello klero2. I don't recall any macro for pull-up resistors in Arduino. You may write your own wrapper quite easily using the DigitalWrite macro. What is the syntax you got in mind? I may give it a try.
